department-of-veterans-affairs/lighthouse-saml-proxy

- Dockerfile
- Jenkinsfile
- package-lock.json
- package.json
- src/routes/handlers.js
Attempt at getting DSLogon assertions to work. I think this will do the job, at least pushing the claims back to Okta, but I can't even get it to run tests. It's failing to install node-gyp and the x509 module, due to some C bindings that don't work with Node 10:
https://github.com/Southern/node-x509/issues/68
Tried merging in your ci fixes branch but that didn't seem to change much.
Giving up for the night.
> Pv dslogon fixes

- config.js
This allows the proxy to map through dslogon-specific claims through to Okta, and then there is corresponding config on the Okta side to map them through to the user profile.
> Add DSLogon claims in config

- README.md
- config.js
- src/SPConfig.js
- src/routes/handlers.js
- src/simpleProfileMapper.js
- Adds profile mapping to support MHV.
- Adds a profile mapping option that supports a transformation method, used to map MHV's complex profile object onto a single account_type string.
- Updates allowed LOAs for DSLogon
- Preserves ID.me-provided authnContext in response path through to Okta.
> MHV support

- oauth-proxy/cli.js
- oauth-proxy/index.js
Don't set default values for access key/id, to allow aws-sdk to read them from instance metadata.
> Make aws key config optional

- oauth-proxy/Dockerfile
Fixed path to health check.
Due to https://github.com/department-of-veterans-affairs/vets-contrib/issues/758, this won't actually make the container show as healthy, but might as well fix this part so it's correct for the eventual health check.
> Fix dockerfile healthcheck path

- oauth-proxy/index.js
Makes sure we pass along the same error responses we get from okta to consumers, so they can debug.
> Pass token error responses downstream

- oauth-proxy/index.js
- saml-proxy/src/app.js
Per guidance here: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-idle-timeout.html
Default was 5 seconds, going to set ELB idle timeout to 60 seconds.
> Set HTTP keepalive timeouts greater than ELB idle timeouts

- saml-proxy/docs/example-idme-profile-received-by-passport.json
- saml-proxy/src/IDMeProfileMapper.test.ts
- saml-proxy/src/IDMeProfileMapper.ts
- saml-proxy/src/VetsAPIClient.test.ts
- saml-proxy/src/VetsAPIClient.ts
As best I can tell, this class pulls double duty and the changes to the test suite adding the `authnContext` attribute were in error. The confusion stems from [this code](https://github.com/department-of-veterans-affairs/vets-saml-proxy/blob/dv-968-fix-upstream-provider-selection/saml-proxy/src/routes/passport.js#L11-L27):
```
return done(null, {
issuer: profile.issuer,
userName: profile.nameIdAttributes.value,
nameIdFormat: profile.nameIdAttributes.Format,
authnContext: {
sessionIndex: profile.sessionIndex,
authnMethod: profile['http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod']
},
claims: new IDMeProfileMapper({claims: omit(
profile,
'issuer',
'sessionIndex',
'nameIdAttributes',
'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier', …
```
> Fix IDMeProfileMapper upstream ID provider detection.

- saml-proxy/src/routes/acsHandlers.ts
This fixes an oversight made in the profile mapper refactor. Need to test in dev because MHV test users are restricted to VA network.
> Use mapped field name for MHV user detection.

- saml-proxy/views/icnLookupFailure.hbs
This error screen is generic to all OAuth interactions, not just health ones. And there's no connection whatsoever to Myhealthevet. I think that was incorrect carry over from some suggested VA.gov error messages.
> Remove MHV/health qualifiers from error message

- Jenkinsfile
This second `agent` directive was causing our builds to sometimes change over to the Jenkins master node, which doesn't have docker installed.
Context:
https://lighthouseva.slack.com/archives/CE79R5SR1/p1554141205032100
https://dsva.slack.com/archives/C7S6EA0ES/p1554142651056000
> Ensure docker stage is run on jenkins swarm node

- oauth-proxy/index.js
Express has a default error handler if a request goes unprocessed. The default error handler spits out a stack trace (when NODE_ENV is not production). I've added two new error handlers. If the request has 'error' and 'error_description' as query params an error handler will display the error and error message. Otherwise a catchall error handler responds with a status of 500 and body of 'An unknown error occured'. The catchall error handler allows us to explicitly control the error message instead of relying on the default from express. I've also updated the error description when a client redirect URI does not match any application redirect URIs.
> Handle unknown errors

- saml-proxy/src/VetsAPIClient.ts
- saml-proxy/src/routes/acsHandlers.test.ts
- saml-proxy/src/routes/acsHandlers.ts
In order to support VSO users in the oauth flow, we need to run a check to see if they exist if MVI fails. This should allow VSO uses to flow through like normal.
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/1823
This is dependent on: https://github.com/department-of-veterans-affairs/vets-api/pull/2991 && https://github.com/department-of-veterans-affairs/vets-contrib/issues/1863
> Attempt VSO Search If MVI Fails

- .gitignore
- oauth-proxy/dynamo_client.js
- oauth-proxy/index.js
- oauth-proxy/jest.config.js
- oauth-proxy/package-lock.json
- oauth-proxy/package.json
- oauth-proxy/tests/backgroundServer.js
- oauth-proxy/tests/e2e.test.js
- oauth-proxy/tests/upstreamOAuthTestServer.js
I started adding CORS support to the oauth-proxy and realized there's no test suite. This adds a few tests to get minimal coverage.
```
-----------------------------|----------|----------|----------|----------|-------------------|
File                         |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------------------------|----------|----------|----------|----------|-------------------|
All files                    |    58.82 |    32.61 |    59.09 |    59.11 |                   |
oauth-proxy                 |    52.63 |    30.95 |    41.38 |    52.94 |                   |
cli.js                     |    66.67 |      100 |        0 |    66.67 |                 4 |
dynamo_client.js           |        8 |        0 |        0 |        8 |... 88,89,90,91,93 | …
```
> Bootstrap test framework and add an end-to-end test for basic coverage.

- oauth-proxy/index.js
- oauth-proxy/package-lock.json
- oauth-proxy/package.json
- oauth-proxy/tests/e2e.test.js
This adds CORS support (both simple and pre-flight) to the metadata endpoints. This allows single page apps (including our react sample app) to auto-configure their OpenID Connect client.
Related to this ticket: https://github.com/department-of-veterans-affairs/vets-contrib/issues/1841
> Add CORS support to metadata endpoints.

- saml-proxy/package-lock.json
- saml-proxy/package.json
- saml-proxy/src/routes/index.js
Solves an error that existed in the SAML Proxy but wasn't exposed because it required a bad signature in the staging env (in the investigation of [vets-contrib #2069](https://github.com/department-of-veterans-affairs/vets-contrib/issues/2069)) to expose the bug. So, generally speaking, I don't think that we need to worry about this happening to an end user, unless there is another way to cause it. The reason is that ID.me will handle actual authentication errors like bad email/password combination - it never sends a `SAMLResponse` back to the SAML Proxy with a failure message to my knowledge in a successfully configured environment. Here's what ID.me does if you enter a bad password or username: 
Alternative solution would be to remove `this.failureFlash = true` in `SPConfig`.
There's …
> Use req.flash properly in passport.authenticate()

- oauth-proxy/index.js
- oauth-proxy/package-lock.json
- oauth-proxy/package.json
- saml-proxy/package-lock.json
- saml-proxy/package.json
Adds express-prom-bundle to the oauth-proxy. Also upgrades it to 5.1.5 for the saml-proxy.
Related to: https://github.com/department-of-veterans-affairs/vets-contrib/issues/2407
> Upgrade express-prom-bundle to 5.1.5 and add it to oauth-proxy.

- oauth-proxy/Dockerfile
- proxy-monitor/Dockerfile
- saml-proxy/Dockerfile
Alpine Node Docker images contain a 'node' user which is intended to run the processes inside the Docker container. Let's use that to run the processes.
> vets-saml-proxy, oauth-proxy, proxy-monitor docker containers run as non-root user

- oauth-proxy/Dockerfile
- proxy-monitor/Dockerfile
- saml-proxy/Dockerfile
fixes: https://github.com/department-of-veterans-affairs/vets-contrib/issues/2525
Alpine node docker containers contain wget, but not curl. Rather than install another package (increase size and attack surface) let's use wget for the healthchecks.
the replacement for this is not 1:1, as curl has different options.
`wget URL -q -O - > /dev/null 2>&1` will take care of it and leave the exit status 0 on success and 1 on failure. `-q` is silent mode, and `-O - > /dev/null 2>&1` causes the output from the wget to be redirected to the bitbucket.
tested inside a proxy-monitor container:
```
/opt/app $ wget localhost:7200/health-check -q -O - > /dev/null 2>&1
/opt/app $ echo $?
0
/opt/app $ wget localhost:7200/health-checak -q -O - > /dev/null 2>&1
/opt/app $ echo $?
1
```
> use wget instead of curl for Docker healthchecks

- oauth-proxy/index.js
- saml-proxy/src/app.js
Hopefully this resolves the 504 issue outlined in https://github.com/department-of-veterans-affairs/vets-contrib/issues/1094.
See my [comment on the issue](https://github.com/department-of-veterans-affairs/vets-contrib/issues/1094#issuecomment-517833070) for my justification of doing this without knowing whether it will help.
Also, 75s is an arbitrary choice, just keeping it the same as the keepalive setting. I don't really have any information to make a better choice, so speak up if you do!
> Increase headersTimeout from default 40s value

- Jenkinsfile
We've cut over the SAML and OAuth proxies to the DVP environments and started to use a different set of Jenkins jobs for deploying to them. This PR makes sure we're triggering deploys to the environments actually in use.
> Trigger dvp deploy jobs

- Jenkinsfile
Update build name from `vets-saml-proxy` to `saml-proxy` after https://github.com/department-of-veterans-affairs/devops/pull/5370 is merged.
> Change build name to saml-proxy

- README.md
This PR fixes broken links to vets-contrib docs caused by repo reorganization.
> Update link to docs in vets-contrib repo

- README.md
- oauth-proxy/index.js
- saml-proxy/src/routes/index.js
Express will use the X-Forwarded-By header for a requests IP address if told to do so. See http://expressjs.com/en/guide/behind-proxies.html. Also fixed a broken link.
> SAML and OAuth proxies configured as such

- oauth-proxy/cli.js
- oauth-proxy/index.js
- oauth-proxy/package-lock.json
- oauth-proxy/package.json
- saml-proxy/package-lock.json
- saml-proxy/package.json
- saml-proxy/src/cli/index.js
- saml-proxy/src/routes/index.js
https://github.com/department-of-veterans-affairs/vets-contrib/issues/2838
Adds sentry reporting to oauth/saml proxies. Secrets are filtered out in `beforeSend`. I found the fields that need to be filtered by watching requests, let me know if you know of any more that need filtered. We could start logging all requests the proxies see in `dev` to look for more but that means we could be logging secrets in `dev`.
There is a bit of duplication between the saml and oauth proxies. Let me know if you can think of a good way of sharing some of the Sentry code across "projects".
~~Leaving as a draft until the Sentry projects get setup. I'm not a Sentry admin so I cannot create the projects myself.~~ I'm now a Sentry Admin (thanks Kalil) and have successfully created the Sentry projects.
> Add sentry to oauth/saml proxies

- saml-proxy/src/routes/acsHandlers.ts
Redirects to `/samlproxy/sp/verify` cause a double render. The double render causes an error to hit [Sentry](http://sentry.vfs.va.gov/vets-gov/saml-proxy/issues/83609/?query=is%3Aunresolved). I don't think this will solve the Apple Health issue, there was no indication that anything was amiss when testing locally.
> Fix double render

- saml-proxy/src/routes/acsHandlers.ts
- saml-proxy/src/utils.js
1. datetime renamed to time to match other time fields
2. log both body and query `RelayState`. Locally I only see relay state in the body but in `dev` I see it in the query params
> Two updates to relay state logging

- saml-proxy/src/cli/index.js
- saml-proxy/src/routes/index.js
This change makes the `saml-proxy` load the session secret from config. This PR will need to wait to be merged until the matching [devops PR](https://github.com/department-of-veterans-affairs/devops/pull/5942) is merged (so the secret is properly populated in the config when deployed).
> Use session secret from config

- saml-proxy/src/metrics.ts
- saml-proxy/src/routes/acsHandlers.test.ts
- saml-proxy/src/routes/acsHandlers.ts
https://github.com/department-of-veterans-affairs/vets-contrib/issues/2393
Add prometheus metrics for MVI and VSO lookups. Using different buckets than the default (.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10) but let me know if I should adjust from what I currently have.
> Add metrics for user lookups

- saml-proxy/src/metrics.ts
https://github.com/department-of-veterans-affairs/vets-contrib/issues/2393
Histograms have three metrics, a count, sum and bucket. This means they shouldn't have bucket in their name. Doing so causes the metrics to be called "name_bucket_bucket", "name_bucket_count" and "name_bucket_sum"
> Metric name shouldn't have bucket

- oauth-proxy/index.js
- oauth-proxy/metrics.js
https://github.com/department-of-veterans-affairs/vets-contrib/issues/3697
This will add one counter to track number of users that have started the OAuth login process. It also will add a counter to track the number of users that have finished the OAuth login process. Together we should be able to get an idea about how many users are failing to complete the login process.
> Add prometheus counters to track oauth login flow

- oauth-proxy/Dockerfile
- saml-proxy/Dockerfile
https://github.com/department-of-veterans-affairs/vets-contrib/issues/3889
All outgoing traffic is intercepted and decrypted by the TIC, meaning our TLS connections are with the TIC, not the external site. Because of that, we need to trust the VA's internal certificate authority that signs the TIC's cert. Node doesn't use the system trust store, so we explicitly add the CA cert with an environment variable: https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file.
> Configure node to trust va's internal certificate authority

- oauth-proxy/index.js
- saml-proxy/src/routes/index.js
https://github.com/department-of-veterans-affairs/vets-contrib/issues/3906
`ShouldHandleError` was defined in the wrong place (see the [docs](https://docs.sentry.io/platforms/node/express/)). Some things to note:
* The oauth proxy returns any error as a 500 error. This 500 wasn't caught by the Sentry error handler because it was set to 500 ***after*** the Sentry error handler is ran.
* I removed an extra error handler that wasn't needed in the oauth proxy
* I moved the Sentry error handler below the `404` middleware in the saml proxy. This ensures 404 errors reach Sentry
> 4xx errors are sent to sentry from oauth/saml proxies

- oauth-proxy/index.js
- oauth-proxy/oauthHandlers/authorizeHandler.js
- oauth-proxy/oauthHandlers/index.js
- oauth-proxy/oauthHandlers/redirectHandler.js
- oauth-proxy/oauthHandlers/tokenHandler.js
- oauth-proxy/tests/e2e.test.js
This should be a 1:1 extraction from index.js for each of these handlers. At this point the function signatures look pretty painful. That reflects just how much of the index.js lexical scope these functions were capturing. With these defines in isolation we can begin testing them as units rather than fully integrated as an express app. This should alleviate the painful function signatures over time, as we find ways to break these down.
> Extract larger route handlers into their own files.

- oauth-proxy/oauthHandlers/tokenHandler.js
- oauth-proxy/oauthHandlers/tokenResponse.js
- oauth-proxy/package-lock.json
- oauth-proxy/package.json
- oauth-proxy/tests/e2e.test.js
- oauth-proxy/tests/oauthHandlers.test.js
When the proxy requests the grant from the upstream oauth server it receives a `TokenSet` object ([docs here](https://github.com/panva/node-openid-client/blob/master/docs/README.md#tokenset)). The library translates the `expires_in` field from the upstream server to an `expires_at` field, translating from a relative timestamp to an absolute timestamp. The proxy was serializing this object directly, causing the client application to see a non-conformant token response that lacked an `expires_in` field. This PR fixes that by making the proxy fully responsible for the shape of the response to the client application.
> Use expires_in instead of expires_at

- Jenkinsfile
Several recent runs of the testing job have failed on master when jenkins is unable to delete the node_modules directory because it's owned by root.
We've only seen the issue on master, so it's hard to say for sure if this will fix it or not.
> Don't run tests as root in container

- oauth-proxy/oauthHandlers/tokenHandler.js
- oauth-proxy/package-lock.json
- oauth-proxy/package.json
- oauth-proxy/tests/e2e.test.js
- oauth-proxy/tests/oauthHandlers.test.js
- oauth-proxy/tests/testUtils.js
- oauth-proxy/utils.js
This should fix [bug #4029](https://github.com/department-of-veterans-affairs/vets-contrib/issues/4029). Essentially the `tokenHandler` error paths were failing to `return`, so we tried to continue processing the request after the error. In addition to that, both error and success paths were not properly calling the `next` expressjs callback. I found this while trying to write the new tests for `tokenHandler` in `oauthHandlers.test.js`. Yay testing! :)
> Make tokenHandler call next() in all paths.

- saml-proxy/test/e2e.test.js
- saml-proxy/test/mockVetsApiClient.ts
- saml-proxy/test/testServer.js
- saml-proxy/test/testUsers.js
https://github.com/department-of-veterans-affairs/vets-contrib/issues/1352
Major changes from the [last PR](https://github.com/department-of-veterans-affairs/vets-saml-proxy/pull/82) are the mock vets-api client is easier to control and the user in the SAMLResponse hitting the `sso` endpoint can be from `idme`, `mhv` or `dslogin`. Note the loop in the e2e test that runs the same tests for all three identity providers.
> Add functional test cases for mhv and dslogin

- oauth-proxy/dev-config.base.json
- oauth-proxy/index.js
- oauth-proxy/oauthHandlers/tokenHandler.js
https://github.com/department-of-veterans-affairs/vets-contrib/issues/4132
See https://lighthouseva.slack.com/archives/CMT4MFPS6/p1580154255007800 and https://lighthouseva.slack.com/archives/CGG5E8CUU/p1580220425011000 for additional context.
This PR fixes a small programming error (using `document.state.S` when `document` might be `undefined`) and ensures that we will actually send a 500 response when encountering an unexpected error. Additionally, it modifies the refresh handler so that errors retrieving the `state` param from DynamoDB will only prevent the `state` from being included in the response, rather than sending an error to the user.
> Fix oauth refresh timeouts

- oauth-proxy/cli.js
- oauth-proxy/dev-config.base.json
- oauth-proxy/index.js
https://vasdvp.atlassian.net/browse/PIV-280
Adds an optional config to override the default 1500ms timeout for OIDC requests.
See https://github.com/department-of-veterans-affairs/devops/pull/6589 for related config changes (15s timeout in non-prod environments).
> PIV-280 - Configurable OIDC timeout

- oauth-proxy/metrics.js
- oauth-proxy/oauthHandlers/tokenHandler.js
- oauth-proxy/package-lock.json
- oauth-proxy/tests/utils.test.js
- oauth-proxy/tokenValidation.js
- oauth-proxy/utils.js
Reapply PIV-260.
The original branch had one import for `stopTimer` that was not updated after moving the function. Was not caught in testing because it requires a specific scope to be requested.
> PIV-260 reapply basic auth parsing

- oauth-proxy/Dockerfile
- oauth-proxy/docker-compose.yml
- saml-proxy/Dockerfile
- saml-proxy/docker-compose.yml
Right now since we are running on two separate platforms, the entrypoint script does not function correctly. 
This bypasses it.
I will create a separate Dockerfile for the fargate process that will not affect this.
> Change Entrypoint to not use entrypoint script

- oauth-proxy/Dockerfile
- oauth-proxy/bin/healthcheck.js
- saml-proxy/Dockerfile
- saml-proxy/bin/healthcheck.js
Since wget, curl, and iwr are all external dependencies, and these services are written in NodeJS, it makes sense to write the healthcheck in NodeJS as well, as the container will _always_ have Node installed.
```[node@f2c91c8b6955 ~]$ ssm-parent --plain-path /dvp/staging/saml-proxy run -- node build/app.js &
[1] 204
[node@f2c91c8b6955 ~]$ {
"service": "saml-proxy",
"env": "development",
"port": 7000,
"level": "info",
"message": "Starting proxy server on port 7000 in development mode",
"time": "2020-04-14T22:11:09.515Z"
}
[node@f2c91c8b6955 ~]$ node bin/healthcheck.js
{
"remote-address": "::ffff:127.0.0.1",
"time": "2020-04-14T22:11:57.522Z",
"method": "GET",
"url": "/samlproxy/idp/metadata",
"status-code": "200",
"content-length": "3763"
}
STATUS: 200
[node@f2c91c8b6955 ~]$ kill -9 204 …
```
> Fix Docker healthchecks by using a nodejs healthcheck

- oauth-proxy/cicd/buildspec-release.yml
- saml-proxy/cicd/buildspec-release.yml
I forgot that the release tagging on these projects uses a prefix with a slash in it. This wont work for tagging ECR images.
This PR uses grep to only get releases for oauth or saml proxy, depending which release is running, and then tags the ECR image with just the part after the "/".
Successful run: https://console.amazonaws-us-gov.com/codesuite/codebuild/projects/saml-proxy-release/build/saml-proxy-release%3A1ad67ff8-8de4-40f3-8df0-e397124fa270/log?region=us-gov-west-1
> Fix release tagging

- oauth-proxy/DockerfileFG
- oauth-proxy/buildspec.yml
- saml-proxy/DockerfileFG
- saml-proxy/buildspec.yml
Using the same dockerfile caused us to have a problem in sandbox and dev yesterday, so to prevent that from occurring again, I will use a separate Dockerfile to develop the pipeline.
> Use a separate Dockerfile to run the Codebuild/Fargate pipeline

- oauth-proxy/apiClients/axiosCachingAdapter.js
- oauth-proxy/apiClients/oktaApiClient.js
- oauth-proxy/index.js
- oauth-proxy/oauthHandlers/authorizeHandler.js
- oauth-proxy/package-lock.json
- oauth-proxy/package.json
- oauth-proxy/tests/oauthHandlers.test.js
- saml-proxy/src/routes/acsHandlers.ts
In accordance to FHIR specifications a check has been added to verify that third parties are sending their access tokens to the proper fhir resource. This will be done via an aud parameter in the /authorization call. The check is optional for the time being but will become mandatory after clients have been given enough time to conform to the standard.
[TestCases](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5057996/API1741_TestCases.docx)
> Api 1741 fhir aud specifications

- oauth-proxy/cli.js
- oauth-proxy/dev-config.base.json
- oauth-proxy/index.js
- oauth-proxy/oauthHandlers/tokenHandler.js
- oauth-proxy/tokenValidation.js
Updated tokenValidation to utilize v1 endpoint including aud in POST
The audience value is directly supplied by Okta in the decoded token, so a simple addition to the new V1 POST endpoint is required.
Note: Corresponding devops repo config changes will be required.
> Updated tokenValidation to utilize v1 endpoint including aud in POST

- saml-proxy/src/routes/handlers.js
Add a check before referencing `forceAuthn`.
https://vajira.max.gov/browse/API-2233
> API-2223 - forceAuthn undefined check

- oauth-proxy/DockerfileFG
We've added support for generating the `config.json` file required by the `oauth-proxy` app. The dockerfile for the deployment into Fargate is being updated to exercise this change.
https://vajira.max.gov/browse/API-1853
https://github.com/department-of-veterans-affairs/health-apis-docker-octopus/pull/34
> API-1853: Support oauth-proxy ECS in Staging 

- oauth-proxy/DockerfileFG
We've added support for generating the config.json file required by the oauth-proxy app. The dockerfile for the deployment into Fargate is being updated to exercise this change. 
- Override the command to point to the newly generated `config.json` file
https://vajira.max.gov/browse/API-1853
department-of-veterans-affairs/health-apis-docker-octopus#34
> API-1853: Support oauth-proxy ECS in Staging (continued)

- saml-proxy/.eslintrc.yml
- saml-proxy/bin/healthcheck.js
- saml-proxy/loadtest/app-idp.js
- saml-proxy/loadtest/app-sp.js
- saml-proxy/src/IDMeProfileMapper.ts
- saml-proxy/src/VetsAPIClient.test.ts
- saml-proxy/src/app.js
- saml-proxy/src/cli/checks.js
- saml-proxy/src/cli/coercing.js
- saml-proxy/src/cli/index.js
- saml-proxy/src/idpMetadata.js
- saml-proxy/src/logger.ts
- saml-proxy/src/metrics.ts
- saml-proxy/src/routes/acsHandlers.test.ts
- saml-proxy/src/routes/acsHandlers.ts
- saml-proxy/src/routes/handlebars.js
- saml-proxy/src/routes/handlers.js
- saml-proxy/src/routes/index.js
- saml-proxy/src/routes/routes.js
- saml-proxy/test/e2e.test.js
- saml-proxy/test/mockVetsApiClient.ts
Added no-unused-vars linting rules to saml-proxy.
[regression tests](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5178575/API1996_RegressionTestsNoUnusedVars.docx)
> Api 1996 saml proxy linting no unused vars

- package-lock.json
- proxy-monitor/package-lock.json
- proxy-monitor/package.json
- saml-proxy/package-lock.json
- saml-proxy/package.json
After regression testing this ticket, it looks like doing the recommended npm installation (npm install uswds@2.8.1) to fix the first yargs-parser vulnerability actually breaks functionality in the saml-proxy service. After rolling back to the original version of uswds (1.6.8) the error no longer occurs. 
I took care of the other yargs-parser vulnerability by updating ts-jest to version 26.3.0. Submitting a PR as is for now.
> Api 2333 update dependencies

- saml-proxy/src/routes/index.js
- saml-proxy/views/error.hbs
Added request id to error pages, so user errors can be easily traced.
[API-2237-Regression-Testing.docx](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5307787/API-2237-Regression-Testing.docx)
> Api 2237 error page displays request

- saml-proxy/.eslintrc.yml
- saml-proxy/loadtest/app-idp.js
- saml-proxy/loadtest/app-sp.js
- saml-proxy/package-lock.json
- saml-proxy/package.json
- saml-proxy/src/cli/checks.js
- saml-proxy/test/e2e.test.js
- saml-proxy/test/testServer.js
Final linting fixes to saml-proxy.
[regression tests](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5343022/API1996_saml_proxy_regression_testing.docx)
> Api 1996 make no undef and no dupe keys errors

- oauth-proxy/package-lock.json
- oauth-proxy/package.json
- oauth-proxy/tests/oauthHandlers.test.js
Okta SDK had outdated version of isomorphic-fetch which had an outdated node-fetch dependency with a security risk. Latest Okta SDK patch fixed this. Updated to latest.
[API2418_Tests__RegressionTests-V2.docx](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5403899/API2418_Tests__RegressionTests-V2.docx)
> Api 2418 update okta sdk

- oauth-proxy/index.js
Setting a custom timeout changed with v 3.0.0 of oidc-client (https://github.com/panva/node-openid-client/tree/v3.15.10/docs#customizing).
Verified timeout is applied by setting it to a low value (400ms) and seeing that a refresh token request occasionally times-out at the given limit.
https://vajira.max.gov/browse/API-3222
> API-2333 - OIDC timeouts

- saml-proxy/DockerfileFG
We've added support for generating the config.json file required by the saml-proxy app. The dockerfile for the deployment into Fargate is being updated to exercise this change.
https://vajira.max.gov/browse/API-1852
Related: #140
> API-1852: Support saml-proxy ECS in Staging

- oauth-proxy/oauthHandlers/tokenHandler.js
- oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/authorizationCodeStrategy.js
- oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/clientCredentialsStrategy.js
- oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/refreshTokenStrategy.js
- oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClient.js
- oauth-proxy/package.json
- oauth-proxy/tests/clientCredentialsStrategy.test.js
- oauth-proxy/tests/e2e.test.js
- oauth-proxy/tests/testUtils.js
- oauth-proxy/tests/tokenHandler.test.js
- oauth-proxy/tests/upstreamOAuthTestServer.js
OAuth Proxy functionality added to support Client Credentials flow for configured trusted consumers.
Only JWT Bearer client_assertion's are valid.  The ICN can be supplied as an additional body arg as `launch`.
JIRA Issue: https://vajira.max.gov/browse/API-3015
> Api 3015 oauth proxy client credentials flow

- oauth-proxy/cli.js
- oauth-proxy/dev-config.base.json
- oauth-proxy/index.js
- oauth-proxy/tests/e2e.test.js
- oauth-proxy/tests/testUtils.js
- oauth-proxy/tokenValidation.js
https://vajira.max.gov/browse/API-3054
Removed all v0 `validate_endpoint` references in favor of the v1 POST endpoint that includes the `aud` validation needed for OAuth isolation.
Note: Unlike most other OAuth proxy PR's, these code changes need to go prior to the devops change due to the `validate_endpoint` being configured as a required parameter
Corresponding Devops change: 
https://github.com/department-of-veterans-affairs/devops/pull/8174
> Removed V0 validation endpoint references.

- oauth-proxy/tests/scripts/assertions.sh
Eliminated the use of temp files in the expect_json_body method. Now the regression tests are compatible with versions of jq under 1.6.
> expect_json_body compares by variables now

- oauth-proxy/dev-config.base.json
- oauth-proxy/index.js
Preliminary PR to removing default routes. Checks for default api_category in the app config. Will use default routes if no default api_category then it will use the default routes.
[API3459-Tests.docx](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5705316/API3459-Tests.docx)
> Api 3459 default category check

- saml-proxy/package-lock.json
- saml-proxy/package.json
Upgraded jest to 26.6.3 to resolve child dependency issue.
Confirmed with the jest upgrade, the jest reporter dependency is updated to `"node-notifier": "^8.0.0"`.
Original dependabot issue:
```
jest@26.4.0 requires node-notifier@^7.0.0 via a transitive dependency on @jest/reporters@26.4.0
```
> Upgraded jest to 26.6.3 to resolve child dependency issue.

- oauth-proxy/cli.js
- oauth-proxy/dev-config.base.json
- oauth-proxy/dynamo_schema.js
- oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/documentStrategies/getDocumentByAccessTokenStrategy.js
- oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentLaunchStrategy.js
- oauth-proxy/tests/dynamo_client.test.js
- oauth-proxy/tests/e2e.test.js
- oauth-proxy/tests/testUtils.js
As part of API-4749 changes to support SSOi the scope of the ClientCredentials table is growing to more than client credentials.  The table is being renamed to LaunchContext since that is its generic purpose for both Client Credentials auth and Authorization Code auth + SSOi.
Tentative plan is a back up and restore (with rename) of the existing Dynamo table in each environment.
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Restore.Tutorial.html
- https://vajira.max.gov/browse/API-4749
- https://github.com/department-of-veterans-affairs/devops/pull/8444 (Dev, Sandbox, Prod)
- https://github.com/department-of-veterans-affairs/lighthouse-oauth-proxy-configs/pull/12 (Staging)
> Api 4749 OAuth proxy rename launch context table

- oauth-proxy/tests/authorizeHandler.test.js
After the SMART launch PR was merged it looks like there are a couple failures on master build that weren't on the PR build.
A `TypeError: Cannot destructure property 'state' of for both failures.` resulted from the missing IDP `mockSlugHelper`.
Add to 2 launch authorize tests to fix.
> Added missing IDP slug parameter to authorize launch tests.

- oauth-proxy/tests/scripts/regression_tests.sh
Use the last working docker image version for regression testing.
> Use docker image version 1.1.2 for regression test script in oauith-proxy

- oauth-proxy/dev-config.base.json
Add new `health/system` route for consumers using client_credentials to access Health APIs.
This route will replace the single purpose `health-insurance` route. Lighthouse will work with existing consumers (1) to migrate them onto `health/system`.
Scopes will be assigned by policy/rule. This allows all system consumers to use the same authz route.
> API-5200 - Add health/system authz route

- oauth-proxy/tests/scripts/other_tests.sh
To Support API-5294, a regression test should be added to the scripted regression test suite for the metadata endpoint.
**Metadata Endpoints**
Endpoints with value checks will be represented by global variables which contain their expected values. If the global variables exists, the tests will check against the values. If they do not exist the test will only check if the value exists.
The global variables are as follows:
- ISSUER = issuer
- AUTHORIZATION_ENDPOINT = authorization_endpoint 
- TOKEN_ENDPOINT = token_endpoint 
- USERINFO_ENDPOINT = userinfo_endpoint 
- INTROSPECTION_ENDPOINT =  introspection_endpoint
- REVOCATION_ENDPOINT = revocation_endpoint 
- JWKS_URI = jwks_uri 
**Expected Results**
**Input**
```sh
export ISSUER=placeholder
export AUTHORIZATION_ENDPOINT=placeholder …
```
> Added Metadata endpoint test

- oauth-proxy/oauthHandlers/authorizeHandler.js
- oauth-proxy/tests/authorizeHandler.test.js
- oauth-proxy/tests/e2e.test.js
Precursor to creating RFC compliant authorize error handling. Refactor previous error handling to eliminate code smells. Reduce nested if statements. 
There are no e2e tests for the authorization endpoint. Add the following:
- Make Authorization request.
- client_store = local
- client_store has redirect `localhost:8080/redirect`
- Make Authorization request.
- client_store = local
- client_store does not have redirect `localhost:8080/redirect`
expected results
```json
{
"error":	"invalid_client",
"error_description": "The redirect URI specified by the application does not match any of the registered redirect URIs. Erroneous redirect URI: http://localhost:8080/redirect"
}
```
- Make Authorization request.
- client_store = local
- specified client not in client_store
expected results …
> Authorize Handler Refactor

- oauth-proxy/oauthHandlers/authorizeHandler.js
- oauth-proxy/tests/authorizeHandler.test.js
- oauth-proxy/tests/e2e.test.js
- oauth-proxy/tests/scripts/other_tests.sh
Authorize Handler should return RFC compliant errors,
```
If the request fails due to a missing, invalid, or mismatching
redirection URI, or if the client identifier is missing or invalid,
the authorization server SHOULD inform the resource owner of the
error and MUST NOT automatically redirect the user-agent to the
invalid redirection URI.
If the resource owner denies the access request or if the request
fails for reasons other than a missing or invalid redirection URI,
the authorization server informs the client by adding the following
parameters to the query component of the redirection URI using the
"application/x-www-form-urlencoded" format, per Appendix B:
...
```
In the case of the Oauth-Proxy
- Issues with the redirect_uri can continue to result in an error page rendered by the …
> RFC compliant authorize error handling

- saml-proxy/cicd/buildspec-ci.yml
- saml-proxy/cicd/buildspec-release.yml
This PR will eliminate the need for CI to call release job. The logic will be replaced by a webhook for push to `master` reference coordinated Terraform PR here https://github.com/department-of-veterans-affairs/devops/pull/8705
> Eliminate calling release job from CI

- oauth-proxy/README.md
- oauth-proxy/dynamo_schema.js
- oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
- oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClientBuilder.js
- oauth-proxy/tests/TokenHandlerTests/saveDocumentStateStrategy.test.js
Add Access Token and ISS to OAuthRequestsV2 on Token requests.
https://github.com/department-of-veterans-affairs/lighthouse-devops-support/issues/280
**note** this index is not required to store the access_token, but will be important for [API-5575](https://vajira.max.gov/browse/API-5575)
**Test Steps**
- Go through Oauth flow on default issuer with no offline access scope. Proves that token flow saves document with no refresh_token,
**Expected Results**
```sh
aws dynamodb scan --table-name OAuthRequestsV2 --endpoint-url http://localhost:8000
```
should return following fields
**Test Steps**
- Go through Oauth flow on default issuer.
**Expected Results**
```sh
aws dynamodb scan --table-name OAuthRequestsV2 --endpoint-url http://localhost:8000
```
should return following fields
**Test …
> Saves access-token and issuer on Token Request

- oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentLaunchStrategy.js
- oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
- oauth-proxy/tests/TokenHandlerTests/saveDocumentLaunchStrategy.test.js
- oauth-proxy/tests/TokenHandlerTests/saveDocumentStateStrategy.test.js
- oauth-proxy/tests/TokenHandlerTests/tokenHandlerTestUtils.js
To support SSOi, the token expiration stored for code and refresh flows should be grabbed from the token object.
~~There is a launch flow for both saveDocumentLaunchStrategy and saveDocumentStateStrategy. The client_credentials access token does not have an `expires_at` or `expires_on` field. There are also cases where this is true for regular token objects reaching the saveDocumentStateStrategy launch block; however, token objects almost always has the expires_in field, which is a long that tell the duration of time when a token will expire. For example a token may expire in 1 hour.~~ 
~~A couple things to consider:~~
- ~~If we intend to save SSOi tokens in the LaunchContext table it may be best to set the expires_at field as `now + expires_in`.~~
- ~~If we do not intend to save SSOi …
> grab exp from token object

- oauth-proxy/cicd/buildspec-ci.yml
- oauth-proxy/cicd/buildspec-release.yml
- saml-proxy/cicd/buildspec-release.yml
This isolates CI for OAuth. Also added to this PR are two more excluded checks for SAML.
Excluding the Jenkins check speeds up the ECS pipeline. The release job will depend solely on the CodeBuild CI job. 
Excluding the SAML check for OAuth and vice versa will ensure release isolation in a case where both products are changed and merged at the same time. 
Web hook PR: 
https://github.com/department-of-veterans-affairs/devops/pull/8747
> isolate release job for oauth

- oauth-proxy/cicd/buildspec-release.yml
- saml-proxy/cicd/buildspec-release.yml
Recent release job failure occurred due too CI webhook not hitting Github prior to gh-status check script kicking off. This is a short term solution while I add a mandatory switch to the `gh-status` tool that will ensure check completes prior to continuing release job.
> add sleep to release jobs

- oauth-proxy/package-lock.json
- oauth-proxy/package.json
Related story: https://vajira.max.gov/browse/API-5673
Upgrading openid-client dependency from version 3.15.10 to 4.4.2. 
Confirmed update with `npm outdated` and tested with regression script.
> upgrade openid-client from 3.15.10 to 4.4.2

- oauth-proxy/cli.js
- oauth-proxy/oauthHandlers/authorizeHandler.js
- oauth-proxy/slug_helper.js
- oauth-proxy/tests/authorizeHandler.test.js
- oauth-proxy/tests/slug_helper.test.js
https://vajira.max.gov/browse/API-6036
Allow the global default IDP to be overridden per authz route.
The IDP will be selected as the first non-empty IDP defined in this order
1. query param
2. authz route
3. global config
Additionally, all these locations now accept a slug, which will be resolved if present in the config.
Config PRs:
* https://github.com/department-of-veterans-affairs/devops/pull/8834
* https://github.com/department-of-veterans-affairs/lighthouse-oauth-proxy-configs/pull/30
> API-6036 - Default IDP per Authz Route

- oauth-proxy/dev-config.base.json
Remove deprecated health-insurance/v1 route
Related story: https://vajira.max.gov/browse/API-5872
Tests:
Unit tests pass.
Regression test script pass locally.
Related PRs: 
https://github.com/department-of-veterans-affairs/lighthouse-oauth-proxy-configs/pull/31
https://github.com/department-of-veterans-affairs/devops/pull/8912
> remove health-insurance/v1 route

- saml-proxy/package-lock.json
- saml-proxy/package.json
https://vajira.max.gov/browse/API-5684
Decided to remove the even-stream dependency, as it was not being used by anything.
> Removing event-stream dependency.

- saml-proxy/package-lock.json
- saml-proxy/package.json
Removing acorn, a dependency that was unused. Verified all functionality with unit and regression tests.
https://vajira.max.gov/browse/API-5682
> API-5682 Remove unused acorn dependency.

- saml-proxy/package-lock.json
- saml-proxy/package.json
Removed node-sass completely. This was not being used in our code. The node-sass-middleware package has its own child dependency of node-sass and there is no need for node-sass to exist at the top level.
Ran all linting and tests and confirmed expected functionality.
Attmpted to update the version of uswds, but it is a peer dependency of @department-of-veterans-affairs/formation and npm throws an error when I update it (even if updating formation to the latest version).
https://vajira.max.gov/browse/API-5680?focusedCommentId=881606&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-881606
> API-5680 Remove node-sass

- saml-proxy/package-lock.json
- saml-proxy/package.json
- saml-proxy/src/metrics.ts
related story: https://vajira.max.gov/browse/API-5677
unit tests pass, regression tests pass, dependencies no longer present in `npm outdated`
> Api 5677 saml prometheus major upgrade

- saml-proxy/package-lock.json
- saml-proxy/package.json
- saml-proxy/test/testServer.js
- saml-proxy/test/utils.test.js
- saml-proxy/tsconfig.json
Update to use original upstream project at https://github.com/auth0/passport-wsfed-saml2 instead of a fork at https://github.com/department-of-veterans-affairs/lighthouse-passport-wsfed-saml2
> API-5707 switch to use auth0/passport-wsfed-saml2

- oauth-proxy/package-lock.json
- saml-proxy/src/SPConfig.js
- saml-proxy/src/routes/handlers.js
- saml-proxy/test/e2e.test.js
For the purposes of trouble shooting, saml requests to IDPs should have unique RequestIDs
I made the request IDs match the express request ID. I think it would be helpful to be able to connect the messages to their express request.
> Add request ids to IDP saml requests

- saml-proxy/package-lock.json
- saml-proxy/package.json
- Updated to uswds 1.6.14
- removed forced trim and postcss dependencies
Note: There was a slight difference in the IDP selection page, but it may be due to me being on a new machine. The changes are only slightly in position, but is unnoticable to the user. See the heatmap below:
> updated to uswds 1.6.14

- .gitignore
- Dockerfile
- Dockerfile.test
- DockerfileFG
- package-lock.json
- package.json
- src/routes/index.js
- src/utils.js
- test/utils.test.js
https://vajira.max.gov/browse/API-7785
- Updates Dockerfiles to use node 16 base image.
- Replaces node-sass and node-sass-middleware with dart-sass and custom middleware.
- Note that the imported CSS from USWDS is using deprecated operations, resulting in warnings from dart-sass when rendering. Safe to ignore, for now
- Upstream issue - https://github.com/uswds/uswds/issues/4204
- Otherwise the generated CSS is functionally equivalent to the previous output.
> API-7785 - Node 16

- Dockerfile.test
- Makefile
- cicd/buildspec-ci.yml
Publish Saml-Proxy-Tests image to ECR.
- The node16 upgrade also upgraded the test image. This broke the test-image build. I didn't catch that, but the way we currently use puppeteer only works with centos 7 and below. The Node 14 and 16 images are based in centos 8. I had to downgrade for this to work.
> Api 8349 publish regression tests

- Makefile
- cicd/buildspec-deploy.yml
- test/regression_tests/README.md
Regression Tests will run on deploy in Dev and Sandbox. 
**Note**: Saml responses are encrypted in staging so some tests cannot run. I have decided to not test upon staging deploy, with some additional work I could probably get the tests that wont work on encrypted responses to be skipped in staging if that is preferable.
https://github.com/department-of-veterans-affairs/devops/pull/9600
Example of a test [failure](https://console.amazonaws-us-gov.com/codesuite/codebuild/008577686731/projects/saml-proxy-deploy/build/saml-proxy-deploy%3A7619a5dd-5149-4003-8a81-08eac22e1b00?region=us-gov-west-1).
Example of test [success](https://console.amazonaws-us-gov.com/codesuite/codebuild/008577686731/projects/saml-proxy-deploy/build/saml-proxy-deploy%3A54c415d8-8db8-402f-bbdf-90e0783cfbb5/?region=us-g …
> Api 8350 run saml proxy regression tests on deploy

- Dockerfile.test
Part of API-8698. Upgrade all images that use puppeteer to Node16.
- Saml-Proxy-Regression tests <- this PR
- https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/pull/341
- Lighthouse-Auth-Utils 
- https://github.com/department-of-veterans-affairs/lighthouse-auth-utils/pull/23
Note: The oauth-proxy regression tests use bats to test, so it is not included in this PR.
Run Regression Test Docker Image
> Updated test docker file to node16

- package-lock.json
- package.json
- tsconfig.json
Somewhere down the line, the package-lock file got outdated and caused the ci builds to fail. This PR fixes those issues.
https://us-gov-west-1.console.amazonaws-us-gov.com/codesuite/codebuild/008577686731/projects/saml-proxy-ci/build/saml-proxy-ci%3Aec8f681f-01ba-4c10-92cf-e6970e98edd8/?region=us-gov-west-1
> Update outdated package-lock dependencies

- Makefile
Fixes an issue where codebuild would report `operand not found` due to quoting issues.
> Update check_tags with properly quoted variable to remove error

- package-lock.json
- src/routes/acsHandlers.test.ts
- src/routes/acsHandlers.ts
- src/routes/constants.ts
- test/e2e.test.js
- test/regression_tests/saml-proxy-regression.test.js
- test/testUtils.js
- test/utils.test.js
The saml-proxy use to redirect to the `/login` page when an assertion response was invalid. The `login` functionality was not supported by the saml-proxy so it has since been deprecated. Now invalid assertion responses will return an error.
```sh
curl http://localhost:7000/samlproxy/sp/saml/sso
```
if in web browser the response will look like this:
> API-9170 | Handle invalid assertion responses.

- src/SPConfig.js
- src/cli/index.js
- src/routes/handlers.js
- src/routes/handlers.test.ts
- views/login_selection.hbs
- Add a button on the saml-proxy UI for a user to register a login.gov account
- This signup button can be enabled or disabled per environment
- In this case the signup page is the login page at login.gov. From there the user can press the "Create an account" button
> API-10491 login gov sign up

- views/login_selection_refactor.hbs
While this does change the styling of the button color, it fixes the monitoring which depends on the class tags for each button (specifically id.me)
> API-000 Add CSP specific class tags back

- src/routes/constants.ts
- src/routes/handlers.test.ts
- src/routes/routes.js
- views/failureToProof.hbs
https://vajira.max.gov/browse/API-11123
Adds support for the failure to proof flow with Login.gov.  To isolate the changes, this defers consolidation of the ID.me federated logins and Login.gov flow.
Login.gov enforces minimum IAL during the login.  This is automatic when logging in with an account that has not yet been identity proofed.  Sandbox url: https://idp.int.identitysandbox.gov/verify/doc_auth/welcome
If an IAL1 user cancels the proofing flow, they are returned to the Lighthouse SAML Proxy where we encourage completion of the proofing process in order to access Lighthouse API's.
> API-11123 Login.gov Failure to Proof Support

- package-lock.json
- package.json
- Addresses a security update to json-schema via an upgrade to http-signature.
- Note, this was done via a forced resolution
- This is a short term fix
- A longer term solution will be addressed by https://vajira.max.gov/browse/API-11511
> API-11508 forced update to http-signature version

- package-lock.json
- package.json
- Addresses a security update to json-schema
- Note, this was done via a forced resolution
- This is a short term fix
- A longer term solution will be addressed by https://vajira.max.gov/browse/API-11511
> forced update for json-schema

- src/SPConfig.js
- src/routes/handlers.js
- src/routes/handlers.test.ts
- Temporary use of a matching cookie to enable the LoginGov IDP via the auth request
- This is for login.gov testing in prod prior to activation
- This is approach nominated for enabling the login.gov idp via the auth  request
Example config segment:
```
{
.
.
.
"idpSamlLoginsEnabled": true,
"idpSelectionRefactor" : true,
"idpSamlLogins": 
[
{
"category": "logingov",
"idpTemporarilyDisabled": true,
"idpActivationCookie": "doublestuffedoreo",
"spIdpMetaUrl": "https://idp.int.identitysandbox.gov/api/saml/metadata2021",
"spNameIDFormat": "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",
"spAudience": "urn:gov:gsa:SAML:2.0.profiles:sp:sso:va_lighthouse:saml_proxy_local",
"spRequestAuthnContext": true,
"spRequestNameIDFormat": true,
"spCert": "./sp-cert.pem",
"spKey": "./sp-key.pem", …
```
> API-12695 cookie activation

- cicd/buildspec-deploy.yml
Fix for CI
https://github.com/department-of-veterans-affairs/lighthouse-devops-support/issues/1174
...
level=error msg="failed to mount overlay: invalid argument" storage-driver=overlay2
...
failed to start daemon: error initializing graphdriver: driver not supported
...
Follow up to the build portion https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/pull/382
> API-000 Fix CI with overlay removal

- src/app.js
- src/idpMetadata.js
Choose the signing key marked as active if more than 1 is available in the IDP metadata
> Choose active signing key if more than 1

- src/app.js
Follow up clean up for scoping `var` vs `let`.
https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/pull/384#discussion_r815951030
> API-000-clean-up-from-code-review

- package-lock.json
- package.json
- test/regression_tests/package.json
Upgrade node-forge package at least v1.0.0 to remove security vulnerabilities.
Issue: https://vajira.max.gov/browse/API-13140
> API-13140 Upgrade Node-Forge

- src/app.js
- src/routes/acsHandlers.ts
ID.me has completed several certificate rotations without proactive notice to Lighthouse.  Unfortunately the SAML Proxy only loads the active certificate at application start up so once the rotation is performed, the responses from ID.me backed IDP's (ID.me, MHV, and DSLogon) fail.
This change logs when an error occurs due to IDP signing key updates.
to force this change line #31 in app.js to:
(sKeyCert) => !sKeyCert.active 
Then serve the app & attempt id.me login
Resulting example:
{
"level": "error",
"message": "Signature check errors: invalid signature: the signature value Bgm5etw36y/SHhVQFZRnnuAprOoYpUXB4g2xZ+vl1EIHA510r1p+VZqB3OszwE9hAlIspSHclukB8C3zQdh7ohYgYPF62R8udMzXocmpcz495j73wbu3vtRDDDoezZZ+HqwQcZIfMDHPTyjSmy/JhyltGXG0lTuchCL26s37RdTdiwlsaZDvZLk5HH1j+EVVh6FQqM9P9d8R295zPshchPT8 …
> added error handler to log passport auth failure

- README.md
- dev-config.base.json
- src/routes/index.js
Logs in the saml-proxy that involve fetching styling elements, such as .css sheets, are distracting to local development and do not add value.
This change allows devs to be able to toggle these on and off using a config option. The default leaves them enabled.
https://vajira.max.gov/browse/API-6846
> Toggle styling logging in saml-proxy

- package-lock.json
- package.json
https://vajira.max.gov/browse/API-21018
Upgrades
- `express` to 4.18.2
- `qs` (via forced resolution) to 6.11.0
```
> saml_proxy_regression_tests@1.0.0 test
> jest -- saml-proxy-regression.test.js
PASS  ./saml-proxy-regression.test.js (91.974 s)
Regression tests
✓ Happy Path (34818 ms)
✓ ICN Error (16542 ms)
✓ Replay (17711 ms)
✓ Empty SSO (1753 ms)
✓ Empty Assertion Response (1944 ms)
✓ 404 (1627 ms)
✓ modify (17248 ms)
Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        92.011 s
```
> API-21018 Fortify Composition Findings

- Dockerfile
- Dockerfile.test
- cicd/buildspec-ci.yml
- cicd/buildspec-deploy.yml
- src/routes/handlers.test.ts
targets ghcr and updates the docker login credentials. 
requires deveps support to add ghcr token, using personal token temporarily to unblock.
https://github.com/department-of-veterans-affairs/lighthouse-devops-support/issues/2425
> API-25655 ghcr node16

- Makefile
- cicd/buildspec-deploy.yml
- test/regression_tests/saml-proxy-regression.test.js
- Added TIMEOUT env variable, so we can easily adjust regression test timeout within param store. 
- Added TIMEOUT to the "modify" regression test, so we can increase as needed.
> API-13875-fix-modify-regression-test

- src/routes/handlers.js
- src/routes/handlers.test.ts
- src/routes/index.js
- Removes code that was causing a SAML ID lookup failure when metadata endpoint called.
> API-000 remove participant

- Dockerfile
Addresses [API-28863](https://jira.devops.va.gov/browse/API-28863)
- Updates the base image used to build the docker image for saml-proxy
> API-28863 saml proxy docker image

- Makefile
Addresses [API-28863](https://jira.devops.va.gov/browse/API-28863)
- Remove workspace override during ci/cd of lint and unit tests
- This will allow for an image change when transitioning to new base image
> API-28863 test and lint, ci-cd

- Dockerfile
Addresses [API-28863](https://jira.devops.va.gov/browse/API-28863)
- Cleans up section needed to work with previous ci setup.
- The PR most proceed https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/pull/462
> API-28863 ci cleanup

- README.md
- package-lock.json
- package.json
Force update browserfy-sign from 4.2.1 to 4.2.2, this is preferable to the alternative which was a major update to uswds
> API-31685 force update browserfy-sign

- src/app.js
Description:
This PR removes the header "x-powered-by" from HTTP responses. This was brought to team Pivot! attention during a WASA scan (Low risk). 
The reason the WASA team wants this header removed, is that it discloses sensitive information about itself and its infrastructure.
Related Issue(s):
https://jira.devops.va.gov/browse/API-29508
> API-29508 Remove Header x-powered-by

- dev-config.base.json
- src/app.js
- src/cli/index.js
- src/idpMetadata.js
To make the retrieving and loading of IDP metadata more stable prior application start up, saml-proxy will first try to make an http request to retrieve IDP metadata before application start up.  If that fails, then saml-proxy will pull the IDP metadata from configs. 
https://jira.devops.va.gov/browse/API-37717
> API-37717 IDP Metadata loads from Config as Fallback

- dev-config.base.json
- src/MpiUserClient.test.ts
- src/MpiUserClient.ts
- src/MpiUserClientConfig.js
- src/app.js
- src/cli/index.js
- src/routes/acsHandlers.test.ts
- src/routes/acsHandlers.ts
- test/testServer.js
This PR is to add the fraud identity theft check in saml-proxy to block any login via the SAML Proxy that is identified to have a Fraud Identity Flag returned from MPI/ICN.
Link to Jira: https://jira.devops.va.gov/browse/API-41014
> API-41014 Fraud Identity Theft

- views/login_selection.ejs
Text changes for DS Logon and My Healthevet.
https://jira.devops.va.gov/browse/API-41180
> API-41180 Text Changes for DS Logon and My Healthevet
