src/routes/handlers.js

Eliminates broken parsing logic, still testing DS Logon but this should at least fix the ID.me path

Fix DSLogon LOA logic

---

views/login_selection.hbs

Fixes https://github.com/department-of-veterans-affairs/vets-contrib/issues/501

Update contact info to va311

---

Jenkinsfile

Once the corresponding Devops PR is in

Add staging auto deploys

---

package-lock.json
package.json
src/routes/index.js

Make sure we're not generating a prom label for each static object

Ep rewrite route labels

---

oauth-proxy/cli.js
oauth-proxy/index.js
oauth-proxy/package-lock.json
oauth-proxy/package.json

Adds a request to the token validation endpoint to get the patient's ICN and includes in the token response.

Add ICN lookup

---

oauth-proxy/cli.js
oauth-proxy/index.js

https://github.com/department-of-veterans-affairs/vets-contrib/issues/2066
Adds idp param to authorize redirect if it's not already present.

Add idp param from config if not set in authorize request

---

.gitignore
oauth-proxy/cli.js
oauth-proxy/dev-config.base.json
oauth-proxy/dynamo_schema.js
oauth-proxy/index.js
oauth-proxy/logger.js
oauth-proxy/package-lock.json
oauth-proxy/package.json
saml-proxy/package-lock.json
saml-proxy/src/IDPConfig.ts
saml-proxy/src/app.js
saml-proxy/src/idpMetadata.js
saml-proxy/src/logger.ts
saml-proxy/src/routes/acsHandlers.ts
saml-proxy/src/routes/handlers.js
saml-proxy/src/routes/index.js

https://github.com/department-of-veterans-affairs/vets-contrib/issues/3568
* Use Winston logger in OAuth proxy
* Create Winston JSON logger 
* Use `timestamp` format in all Winston loggers on top of JSON (do we prefer "timestamp" or "time" for this property name - is one more consistent with other components or have conflicts, or is it sort of a 6 on one hand, half dozen on the other type of decision?)
* Some updates to improve running OAuth proxy locally

Convert OAuth and SAML proxy logs to JSON and add timestamp

---

Jenkinsfile
saml-proxy/package-lock.json
saml-proxy/package.json

https://github.com/department-of-veterans-affairs/vets-contrib/issues/3671
More tests to come, but for now we should at least make sure the existing oauth proxy tests get run on each commit.

Run oauth proxy tests on jenkins

---

oauth-proxy/dev-config.base.json
oauth-proxy/index.js
oauth-proxy/logger.js
saml-proxy/package-lock.json
saml-proxy/package.json

follow-up to https://github.com/department-of-veterans-affairs/vets-contrib/issues/3568. did not fix the morgan middleware in #69. see https://lighthouseva.slack.com/archives/CKBG69DM1/p1575976259051600
also some `npm audit fix` changes

Fix OAuth proxy middleware logging to be JSON

---

oauth-proxy/tests/e2e.test.js

This is a test that documents current behavior. There's a bug in this functionality that will require changing this test. The next PR will be cleaner with this test added in isolation.

Add test for the token endpoint response body.

---

oauth-proxy/tokenValidation.js

d'OH!
I'll add a test for this in my next PR. This is causing errors in dev right now though.

Fix configureTokenValidator

---

oauth-proxy/metrics.js
oauth-proxy/oauthHandlers/tokenHandler.js
oauth-proxy/tokenValidation.js
oauth-proxy/utils.js

Add timing metrics through oauth-proxy flow.
related story: https://vasdvp.atlassian.net/browse/PIV-216

Piv 216 additional oauth proxy timing metrics

---

oauth-proxy/metrics.js
oauth-proxy/oauthHandlers/tokenHandler.js
oauth-proxy/tests/utils.test.js
oauth-proxy/utils.js

https://vasdvp.atlassian.net/browse/PIV-260
Adds better handling for malformed basic authorization headers.

PIV-260 - Better Basic Auth Handling

---

oauth-proxy/cicd/README.md
oauth-proxy/cicd/buildspec-manual-deploy.yml
saml-proxy/cicd/README.md
saml-proxy/cicd/buildspec-manual-deploy.yml

Adds a readme and manual deploy option.

add readme and deploy scripts

---

CODEOWNERS

Added Pivot code owners file.

---

oauth-proxy/oauthHandlers/authorizeHandler.js
oauth-proxy/tests/oauthHandlers.test.js

Don't redirect, send out error

API-1524-validate-redirects-and-forwards 

---

saml-proxy/src/routes/acsHandlers.ts

Removed extra logging

---

oauth-proxy/oauthHandlers/authorizeHandler.js
oauth-proxy/tests/oauthHandlers.test.js

Audit audience parameter passed to `/authorization`.

API-1741 - Log audience

---

saml-proxy/package-lock.json
saml-proxy/package.json

Upgraded dependencies to address dependencies on older versions of dot-prop and braces

Api 1943 vets saml proxy update dependencies

---

saml-proxy/src/routes/handlers.js
saml-proxy/src/routes/handlers.test.ts

Fixed error in loginhandler cause by previous linting PR.
[regressionTests](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5171623/API1996_regressionTests_V2.docx)

Api 1996 reduce error fix

---

saml-proxy/src/routes/handlers.js

[Findings and Tests](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5228383/API2231_Findings_And_Tests.docx)

Added import for extend module in handlers.js

---

oauth-proxy/oauthHandlers/redirectHandler.js

Fix linting warning.
Related issue: https://vajira.max.gov/browse/API-2228

fix linting warning

---

saml-proxy/loadtest/app-idp.js
saml-proxy/src/routes/constants.ts
saml-proxy/src/routes/handlers.js
saml-proxy/src/routes/routes.js

Remove unused IDP sign-in functionality.
https://vajira.max.gov/browse/API-2445

Api 2445 remove idp signin

---

oauth-proxy/buildspec.yml
saml-proxy/buildspec.yml

Required changes to fix codebuild.

fix codebuild

---

saml-proxy/package-lock.json
saml-proxy/src/routes/handlers.js
saml-proxy/src/routes/handlers.test.ts
saml-proxy/src/routes/index.js

Logged and threw error message for the case of when someone is trying to authenticate without a relay state.
https://vajira.max.gov/browse/API-2249

API-2249 - Reject missing redirect

---

saml-proxy/package-lock.json
saml-proxy/package.json

References our forked version of passport-wsfed-saml2.

Api 3115 passport wsfed saml2

---

Jenkinsfile
oauth-proxy/.eslintrc.yml
oauth-proxy/index.js
oauth-proxy/oauthHandlers/tokenHandler.js
oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/authorizationCodeStrategy.js
oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/refreshTokenStrategy.js
oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClient.js
oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/unsupportedGrantStrategy.js
oauth-proxy/package-lock.json
oauth-proxy/package.json
oauth-proxy/tests/tokenHandler.test.js
saml-proxy/DockerfileFG
saml-proxy/package-lock.json
saml-proxy/package.json

Uses a forced resolution to address a security finding for node-forge.

Api 2512 forced resolution

---

oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/getPatientInfoStrategies/getPatientInfoFromValidateEndpointStrategy.js
oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
oauth-proxy/tests/getPatientInfoFromValidateEndpointStrategy.test.js

Validation errors will now be sent to sentry.

Api 3381 token handler 500 errors to sentry

---

oauth-proxy/dev-config.base.json

Add PGD auth routes.
https://vajira.max.gov/browse/API-3928

API-3928 - Add auth routes for PGD

---

oauth-proxy/index.js
oauth-proxy/tests/e2e.test.js

Remove references to  const appRoutes in index.js and replace them with config.routes.app_routes.

Api 3633 oauth proxy remove routes const

---

saml-proxy/DockerfileFG

https://vajira.max.gov/browse/API-3865
- set docker labels
- update config file path to EFS mount path

SAML Proxy DockerFG use EFS mount path

---

oauth-proxy/package.json
saml-proxy/package.json

Update project metadata

---

oauth-proxy/oauthHandlers/authorizeHandler.js
oauth-proxy/tests/authorizeHandler.test.js
oauth-proxy/tests/scripts/other_tests.sh
oauth-proxy/tests/scripts/regression_tests.sh

Added a simple check for redirect uri with an oauth2 compliant error message at the beginning of /authorization middleware function.

API 4280 Verify redirect uri is present earlier.

---

oauth-proxy/index.js
oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/getPatientInfoStrategies/getPatientInfoFromValidateEndpointStrategy.js
oauth-proxy/package-lock.json
oauth-proxy/tests/TokenHandlerTests/getPatientInfoFromValidateEndpointStrategy.test.js
oauth-proxy/tests/cornerCaseE2e.test.js
oauth-proxy/tests/e2e.test.js

Changed the Oauth-Proxy to handle validation errors as 503 to indicate the service is temporarily unavailable.
The following is a list of the current Token Handler Tests:
- Token Handler code happy path
- Token Handler expired code
- Token Handler invalid code
- Token Handler code path invalid client id
- Revoke active token happy path
- Token Handler refresh happy path
- Token Handler invalid refresh Token
- Token Handler refresh path invalid client id
- Client Credentials happy path
- Token Handler invalid strategy
- Token Handler missing grant_type
There is currently no test for Validation Errors, because it is not possible to force Vets-API to throw an error on validation. Work arounds would be to mock this out or to point the validation post endpoint in the Oauth Proxy config to a …

Api 4185 503 error handling for validation endpoint

---

oauth-proxy/cli.js
oauth-proxy/dynamo_schema.js

- Add a new table to the local developer setup.
- Shows the table addition to be proposed in an upcoming MR

Api 4961 client table

---

saml-proxy/package.json
saml-proxy/src/routes/handlers.js
saml-proxy/src/routes/handlers.test.ts

- Uses query parameter to get relay state
- More unit tests

Api 4620 basic account behavior fix

---

oauth-proxy/tests/scripts/token_tests.sh

- Add check for a test with staging for the client credentials flow.

cctest staging

---

oauth-proxy/tests/TokenHandlerTests/saveDocumentStateStrategy.test.js

To prepare for API-5572 new assertions were added to saveDocumentStateStrategyTests

Added more specific dynamo assertions to saveDocumentStateStrategyTests

---

oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js

Following the question on the need for this block, added 42 day callout for fallback logic.

Added 42 day callout for fallback logic.

---

oauth-proxy/cli.js
oauth-proxy/dev-config.base.json

API-5573 Add configuration flag for handling opaque tokens.

---

oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClient.js
oauth-proxy/package-lock.json
oauth-proxy/tests/TokenHandlerTests/saveDocumentStateStrategy.test.js
oauth-proxy/tests/TokenHandlerTests/tokenHandlerClient.test.js
oauth-proxy/tests/TokenHandlerTests/tokenHandlerTestUtils.js

- tokenHandlerClient
- saveDocumentStateStrategy

Grab Scopes from Token Objects instead of Access Token

---

saml-proxy/package-lock.json
saml-proxy/package.json

Remove yargs-parser dependency, which is vulnerable and unused
Ran full regression tests on branch.

Removed yargs-parser

---

oauth-proxy/oauthHandlers/authorizeHandler.js
oauth-proxy/tests/authorizeHandler.test.js

related story: https://vajira.max.gov/browse/API-6136

remove aud warning logging

---

saml-proxy/package-lock.json
saml-proxy/package.json
saml-proxy/src/routes/index.js

UUID dependency should be updated: 3.4.0 -> 8.3.2

Update saml proxy UUID

---

saml-proxy/package-lock.json
saml-proxy/package.json

- Note that issue was the result of a deep dependency chain.
- There is a followup to this effort.
- See https://vajira.max.gov/browse/API-7074

API-7029 Forced resolution required for postcss

---

saml-proxy/cicd/buildspec-release.yml

Related story: https://vajira.max.gov/browse/API-6997

Include release name in vabot slack notification

---

saml-proxy/package-lock.json
saml-proxy/package.json

- Upgraded 'normalize-url' using resolutions.
- This was a transitive dependency via 'nodemon', of which this project is using the latest release

API-8085 normalize-url >= 4.5.1

---

.gitallowed
test/regression_tests/package-lock.json
test/regression_tests/package.json

https://vajira.max.gov/browse/API-8329
Move the saml-utils repo to VA organization.

API-8329 - Move saml-utils repo

---

Makefile
cicd/buildspec-deploy.yml

* https://vajira.max.gov/browse/API-6867
* Adds small script to Makefile to check if tag exists in ECR
* Adds make target during deployment process to verify tag exists to prevent long lived deployment failures. 
Deployment with Tag that does not exist:https:
https://lighthouseva.slack.com/archives/C01CP09F04Q/p1630355720004200

Check that image with tag exists prior to deployment

---

.husky/commit-msg
.husky/pre-commit
.husky/prepare-commit-msg
package-lock.json
package.json

Husky will be installed on`npm run prepare`, which run on `npm install`. Then the pre-commit script will check for aws-secret patterns and our local `/git-secrets-patterns`. If they are not it will add the values. Then it will run all the git-secrets scripts on commit. There is no way to run the oauth-proxy without initializing git secrets. For testing this branch you may want to run `npm run prepare` to avoid a fresh install.
It may be work running eslint on git pushes.

API-8331 | add husky hooks

---

package-lock.json
package.json
src/IDPConfig.ts
test/e2e.test.js

API-000 | Update xmldom dependency

---

dev-config.base.json
src/cli/index.js

Updated dev-config.base.json to stay in sync with recent changes

---

package-lock.json
test/regression_tests/package-lock.json

Tmpl dependency is a nested dependency so running npm update on the base project and regression_test project did the trick.

Api 10511 | upgrade tmpl dependency

---

README.md

Updated readme for Lighthouse specific naming

Updated readme for Lighthouse specific naming

---

package-lock.json
package.json

- Used resolution to force xml-crypto >= 2.1.3

API-11410 xml crypto update

---

README.md

- Update README to reflect current functionality.

API-10735 readme update

---

package-lock.json
test/regression_tests/package-lock.json
test/regression_tests/package.json

Related story: https://vajira.max.gov/browse/API-13139
Upgrade puppeteer to upgrade node-fetch

upgrade puppeteer to 13.3.0

---

views/login_selection.hbs

Update FAQ link to point to production instead of staging.
issue: https://vajira.max.gov/browse/API-14287

API-14287 Update FAQ Link

---

src/SPConfig.js
src/routes/handlers.js
src/routes/handlers.test.ts

Removes idpActivationCookie and idpTemporarilyDisabled for Login.gov testing with cookie and related tests.
issue: https://vajira.max.gov/browse/API-14655
Follow up by removing idpTemporarilyDisabled from saml-proxy-configs

API-14655 Remove Login.gov Cookie

---

package-lock.json
package.json

force upgrade ejs
story: https://vajira.max.gov/browse/API-16121

API-16121 force upgrade ejs

---

package.json
test/regression_tests/package-lock.json

Address https://vajira.max.gov/browse/API-16122
- Upgrades moment to 2.29.2 or greater.

API-16122 moment >= 2.29.2

---

package-lock.json
package.json

fix vulnerability
https://vajira.max.gov/browse/API-17422

moment >=2.29.4

---

package-lock.json

Addresses https://vajira.max.gov/browse/API-17423
- Updating package-lock using 'npm audit fix' removed the dependency on 'got' altogether.

API-17423 update got

---

package-lock.json
package.json
src/routes/acsHandlers.ts

Addresses https://vajira.max.gov/browse/API-17423
- Upgrades passport to >= 0.6.0

API-17423 passport upgrade

---

test/regression_tests/saml-proxy-regression.test.js

API-000 replace all page.click

---

package-lock.json
package.json
test/regression_tests/package-lock.json
test/regression_tests/package.json

https://vajira.max.gov/browse/API-21096
Address:
https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/security/dependabot/26

Api 21096 upgrade xmldom

---

test/regression_tests/package-lock.json
test/regression_tests/package.json

Addresses https://vajira.max.gov/browse/API-24513

API-24513 upgrade puppeteer

---

src/routes/acsHandlers.test.ts
src/routes/acsHandlers.ts

Preserves original IDP values for null occurrence of either first or last name.

API-000 null first last name mpuser

---

src/IDPProfileMapper.test.ts
src/MpiUserClient.test.ts
src/routes/acsHandlers.test.ts
src/routes/acsHandlers.ts
src/routes/handlers.test.ts
test/mockMpiUserClient.ts

This PR is to resolve the typescript errors that exist in various files.
Link to JIRA: https://vajira.max.gov/browse/API-25720

Api 25720 Typescript Errors

---

package-lock.json
package.json
test/regression_tests/package-lock.json

- updates saml-attack
- updates xmljs

API-25934 update saml-attack and xmljs

---

test/user_tests/package-lock.json

update /test/user_tests > saml-attacks

API-000 update saml-attacks

---

.gitignore
package.json
src/IDPConfig.ts
src/routes/acsHandlers.ts
test/SAMLResponse.example.xml
test/e2e.test.js

Includes InResponseTo property in idp SAML response to support Okta update.

API-25662 adds InResponseTo SAML attribute

---

test/regression_tests/package-lock.json
test/regression_tests/package.json
test/user_tests/package-lock.json
test/user_tests/package.json

**Description:** 
Update semver dependency, due to Dependabot alert security vulnerability. 
**Related Issues:** 
https://jira.devops.va.gov/browse/API-28173
**A/C:** 
Dependabot dependency alert remediated.

Semver Dependency Update

---

src/routes/acsHandlers.ts
src/utils.js

Description:
saml-proxy logging of relay state may warrant some level of relay state validation if not already present.
Related Issues:
https://jira.devops.va.gov/browse/API-28193
A/C:
CodeQL log injection alert's not showing up on lighthouse-saml-proxy repo.

API-28193 Log injection mitigation

---

src/routes/index.js

This PR is to address this codeql scan alert:
https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/security/code-scanning/10
Link to Jira: https://jira.devops.va.gov/browse/API-28191

API-28191 codeql sensitive cookie

---

src/routes/handlers.js

This PR address this codeql scan alert:
https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/security/code-scanning/16
Link to Jira: https://jira.devops.va.gov/browse/API-28190

API-28189 codeql superfluous argument

---

src/idpMetadata.js
src/routes/handlers.js

This PR addresses a multiple codeql scan alert that deal with expressions that have no effect:
https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/security/code-scanning/15
Link to Jira: https://jira.devops.va.gov/browse/API-28189

API-28189 codeql expression has no effect

---

src/routes/acsHandlers.ts
src/utils.js
test/utils.test.js

**Description:**
saml-proxy logging of relay state may warrant some level of relay state validation if not already present.
**Related Issues:**
https://jira.devops.va.gov/browse/API-28193
**A/C:**
CodeQL log injection alert's not showing up on lighthouse-saml-proxy repo.

Log injection Fix

---

package-lock.json

Addresses https://jira.devops.va.gov/browse/API-28176
- Updates work-wrap-dependency

API-28176 npm audit fix work-wrap-dependency

---

package-lock.json
package.json
src/routes/acsHandlers.test.ts
src/routes/acsHandlers.ts
src/routes/handlers.js
src/routes/handlers.test.ts
src/routes/index.js
src/routes/types.ts
src/utils.js
test/e2e.test.js
test/testUtils.js

- Removes session dependency
- Abstracts ID and ReplayState retrieval
- Removes some repetitive req var stashing.

API-28822 remove session

---

Dockerfile.test

Addresses [API-28863](https://jira.devops.va.gov/browse/API-28863)
- Updates the base image for the saml proxy regression tests container

API-28863 saml proxy docker image regression tests

---

package-lock.json
package.json

**Decsription:** 
The following Lodash modules were added to saml-proxy package.json
1.     "lodash.includes": "^4.3.0",
2.     "lodash.isboolean": "^3.0.3",
3.     "lodash.isinteger": "^4.0.4",
4.     "lodash.isnumber": "^3.0.3",
5.     "lodash.isplainobject": "^4.0.6",
6.     "lodash.once": "^4.1.1"

API-000 Add Lodash Modules

---

Dockerfile.test
cicd/buildspec-ci.yml
test/regression_tests/package-lock.json
test/regression_tests/package.json
test/regression_tests/saml-proxy-regression.test.js

API-000 fix pipeline

---

test/user_tests/package-lock.json

Update dependencies for usertests

API-31886 update dependencies usertests

---

test/regression_tests/modifyAttack.js
test/regression_tests/package-lock.json
test/regression_tests/package.json
test/regression_tests/saml-proxy-regression.test.js

Restores the  modify attack regression test.
To test against sandbox.
```
cd test/regression_tests
source path/to/env.sh
export IDP=lighthouse
npm i
npm test
```
Then observe the result.
```
Regression tests
✓ Happy Path (20289 ms)
✓ ICN Error (19178 ms)
✓ Replay (21316 ms)
✓ Empty SSO (3264 ms)
✓ Empty Assertion Response (2514 ms)
✓ 404 (2555 ms)
✓ modify (16461 ms)
```

API-000 restore modify test

---

Dockerfile.test

API-000 Fix test image build in ci

---

test/e2e.test.js

attempting to clear/test ci pipeline

API-000 arbitrary change

---

package-lock.json

This PR is to address the dependabot issue below:
https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/security/dependabot/66

API-000 Dependabot Issue 

---

package-lock.json
package.json

Addresses dependabot findings.
- Reference https://jira.devops.va.gov/browse/API-35218

API-35218 dependabot

---

package-lock.json
test/regression_tests/package-lock.json
test/user_tests/package-lock.json

First pass ad addressing dependabot findings.

API-000 npm audit fix

---

package-lock.json

This PR is to revert the package-lock.json changes that are causing dependabot issues

API-000 Fix package-lock.json

---

Dockerfile.test

API-38630-chrome-dl-fix

---

styles/core.scss
views/login_selection.ejs

- reduces font size on mobile and widens max width to acomodate title length

API-000 mobile overrides

---

package-lock.json
test/regression_tests/package-lock.json
test/regression_tests/package.json
test/user_tests/package-lock.json
test/user_tests/package.json

This PR is to address the dependabot findings:
https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/security/dependabot

API-40067 dependabot findings

---

package-lock.json
test/regression_tests/package-lock.json
test/regression_tests/package.json
test/user_tests/package-lock.json
test/user_tests/package.json

Reverts department-of-veterans-affairs/lighthouse-saml-proxy#506

Revert "API-40067 dependabot findings"

---

package-lock.json
package.json

Reverts department-of-veterans-affairs/lighthouse-saml-proxy#510

Revert "API-41803 address dependabot findings"

---

package-lock.json
package.json

PR to address dependabot findings

PR-41083 address depandabot findings

---

.github/workflows/ci.yml
Dockerfile
Makefile
cicd/buildspec-ci.yml

This PR is to remove UT/linting from code build and move it to gh actions
Link to Jira: https://jira.devops.va.gov/browse/API-41055

API-41055 UT/linting to GH actions

---

views/login_selection.ejs

SAML Proxy UI to de emphasise MHV and DSLogon IDP's.
https://jira.devops.va.gov/browse/API-41180

API-41180 De Emphasise MHV and DSLogon IDP's

---

views/login_selection.ejs

- Updates MHV removal date
- Does not incorporate any other UI changes

API-44394 update mhv removal date

---

views/internal_failure.ejs
views/sensitive_error.ejs

This PR changes the url for the error page

API-000 url change

---

package-lock.json

API-46095 xml-cryto items

---

package-lock.json

Reverts department-of-veterans-affairs/lighthouse-saml-proxy#532

Revert "API-000 dependabot findings"
